## e009 EDA
 * group 内の preds を使う

In [1]:
import pandas as pd
import numpy as np
import gc
import pickle
import pyarrow.parquet as pq
from multiprocessing import Pool
from tqdm import tqdm_notebook as tqdm

import scipy
from scipy import signal
from scipy.signal import butter

from matplotlib import pyplot as plt
import seaborn as sns

import sys
sys.path.append('../../guchio_utils/')

In [2]:
#plt.rcParams['font.family'] = 'IPAPGothic' #全体のフォントを設定
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))
# %config InlineBackend.figure_formats = {'png', 'retina'}
%load_ext autoreload
%autoreload 1

### OOF analysis

In [2]:
#trn_df = pd.read_parquet('../inputs/origin/train.parquet.zip', compression='zip')
trn_df = pq.read_pandas('../inputs/origin/train.parquet').to_pandas()
trn_meta_df = pd.read_csv('../inputs/origin/metadata_train.csv')

In [3]:
trn_hp_dn_df = pd.read_pickle('../inputs/prep/train_hp_dn.pkl.gz', compression='gzip')
trn_hp_dn_df.head()

0         1          2          3         4          5          6  \
0  13.601562  0.000906 -14.601562 -14.359375 -4.300781  17.921875  -8.484375   
1  16.234375  0.000906 -17.515625 -17.390625 -5.820312  21.062500  -9.898438   
2  11.335938  0.000906 -12.445312 -14.546875 -4.878906  18.562500 -11.429688   
3  12.453125  0.000906 -13.718750 -14.234375 -4.585938  18.843750 -12.609375   
4  17.343750  0.000906 -18.937500 -13.914062 -3.957031  19.437500 -13.406250   

           7         8          9    ...           8702       8703       8704  \
0   6.421875 -0.000802 -13.218750    ...      15.773438 -17.171875  10.335938   
1   9.070312 -0.000802 -15.539062    ...      18.187500 -21.968750  12.976562   
2  12.156250 -0.000802 -12.531250    ...      14.906250 -17.859375  11.609375   
3  14.265625 -0.000802 -11.726562    ...      14.937500 -18.078125  11.570312   
4  15.304688 -0.000802 -11.187500    ...      15.960938 -19.500000  11.343750   

       8705       8706      8707       8708       8709      8710       8711  
0  6.441406  11.609375  3.173828 -20.593750 -13.429688 -6.679688  17.515625  
1  7.500000  14.734375  4.218750 -18.437500 -16.000000 -7.945312  22.015625  
2  5.574219  13.398438  5.417969 -17.937500 -13.179688 -5.648438  20.375000  
3  6.031250  13.648438  6.257812 -16.890625 -13.085938 -6.136719  21.187500  
4  7.976562  13.796875  6.699219 -17.671875 -13.539062 -8.343750  21.234375  

[5 rows x 8712 columns]

### 再度 oof 

In [10]:
# with open('../oofs/e007_2019-01-16-14-34-03_0.5397_0.17_oofs.pkl', 'rb') as fin:
with open('../oofs/e008_2019-01-16-17-15-02_0.5383_0.207_oofs.pkl', 'rb') as fin:
    oof = pickle.load(fin)

In [11]:
oof

[[array([   3,    4,    5, ..., 8709, 8710, 8711]),
  array([  15,   16,   17, ..., 8691, 8692, 8693]),
  array([  12,   13,   14, ..., 8706, 8707, 8708]),
  array([   0,    1,    2, ..., 8700, 8701, 8702]),
  array([   6,    7,    8, ..., 8697, 8698, 8699])],
 [array([0.14339742, 0.38784939, 0.36013803, ..., 0.2877849 , 0.0070246 ,
         0.02295375]),
  array([1.44399327e-04, 1.11547420e-05, 1.44386204e-04, ...,
         2.93916138e-05, 6.45865418e-06, 1.28585802e-05]),
  array([3.24142288e-04, 2.32358380e-02, 1.85473408e-03, ...,
         2.66883710e-05, 4.97293663e-05, 8.87931803e-06]),
  array([8.08961869e-02, 1.54722635e-02, 5.84360722e-03, ...,
         7.18891119e-06, 9.63243261e-06, 2.41244634e-05]),
  array([5.42586989e-04, 1.06259744e-03, 7.84617530e-05, ...,
         1.21294673e-05, 4.22545563e-05, 3.59573441e-05])]]

In [12]:
len(oof), len(oof[0]), len(oof[1]), 

(2, 5, 5)

In [75]:
def place_0(x):
    return x.iloc[0]

def place_1(x):
    return x.iloc[1]

def place_2(x):
    return x.iloc[2]

def y_preds_features(oofs, val_idxes):
    # Make the base df
    y_preds_df = pd.DataFrame()
    y_preds_df['signal_id'] = np.concatenate(val_idxes).astype(int)
    y_preds_df['y_pred'] = np.concatenate(oofs).astype('float64')
    y_preds_df['id_measurement'] = (y_preds_df['signal_id']//3).astype(int)
    y_preds_df.sort_values('signal_id', inplace=True)
    y_preds_df.reset_index(drop=True, inplace=True)
    
    # Agg
    agg_y_preds_df = y_preds_df.groupby('id_measurement').agg({
        'y_pred': ['max', 'min', 'mean', 'std', place_0, place_1, place_2]
    })
    agg_y_preds_df.columns = [e[0] + '_' + e[1] for e in agg_y_preds_df.columns]
    
   # Merge 
    y_preds_df = y_preds_df.merge(agg_y_preds_df, on='id_measurement', how='left').drop(['signal_id', 'id_measurement'], axis=1)
    return y_preds_df

In [79]:
y_preds_features([oof[1][0]], [oof[0][0]])

y_pred  y_pred_max  y_pred_min  y_pred_mean    y_pred_std  \
0     0.143397    0.387849    0.143397     0.297128  1.338539e-01   
1     0.387849    0.387849    0.143397     0.297128  1.338539e-01   
2     0.360138    0.387849    0.143397     0.297128  1.338539e-01   
3     0.000098    0.374848    0.000098     0.133614  2.093120e-01   
4     0.025898    0.374848    0.000098     0.133614  2.093120e-01   
5     0.374848    0.374848    0.000098     0.133614  2.093120e-01   
6     0.000005    0.000075    0.000005     0.000037  3.586883e-05   
7     0.000030    0.000075    0.000005     0.000037  3.586883e-05   
8     0.000075    0.000075    0.000005     0.000037  3.586883e-05   
9     0.063963    0.063963    0.015281     0.033575  2.649898e-02   
10    0.015281    0.063963    0.015281     0.033575  2.649898e-02   
11    0.021481    0.063963    0.015281     0.033575  2.649898e-02   
12    0.000027    0.000027    0.000007     0.000017  9.873897e-06   
13    0.000016    0.000027    0.000007     0.000017  9.873897e-06   
14    0.000007    0.000027    0.000007     0.000017  9.873897e-06   
15    0.000680    0.004194    0.000680     0.002750  1.839158e-03   
16    0.003376    0.004194    0.000680     0.002750  1.839158e-03   
17    0.004194    0.004194    0.000680     0.002750  1.839158e-03   
18    0.000003    0.000012    0.000001     0.000005  5.586911e-06   
19    0.000001    0.000012    0.000001     0.000005  5.586911e-06   
20    0.000012    0.000012    0.000001     0.000005  5.586911e-06   
21    0.037392    0.360966    0.037392     0.152802  1.806310e-01   
22    0.060047    0.360966    0.037392     0.152802  1.806310e-01   
23    0.360966    0.360966    0.037392     0.152802  1.806310e-01   
24    0.000039    0.001000    0.000026     0.000355  5.588195e-04   
25    0.000026    0.001000    0.000026     0.000355  5.588195e-04   
26    0.001000    0.001000    0.000026     0.000355  5.588195e-04   
27    0.000076    0.000268    0.000050     0.000131  1.189313e-04   
28    0.000268    0.000268    0.000050     0.000131  1.189313e-04   
29    0.000050    0.000268    0.000050     0.000131  1.189313e-04   
...        ...         ...         ...          ...           ...   
1713  0.001370    0.001370    0.000176     0.000627  6.487944e-04   
1714  0.000334    0.001370    0.000176     0.000627  6.487944e-04   
1715  0.000176    0.001370    0.000176     0.000627  6.487944e-04   
1716  0.000012    0.000043    0.000007     0.000021  1.922226e-05   
1717  0.000043    0.000043    0.000007     0.000021  1.922226e-05   
1718  0.000007    0.000043    0.000007     0.000021  1.922226e-05   
1719  0.000007    0.000036    0.000001     0.000015  1.871452e-05   
1720  0.000036    0.000036    0.000001     0.000015  1.871452e-05   
1721  0.000001    0.000036    0.000001     0.000015  1.871452e-05   
1722  0.000005    0.000005    0.000004     0.000005  8.463908e-07   
1723  0.000005    0.000005    0.000004     0.000005  8.463908e-07   
1724  0.000004    0.000005    0.000004     0.000005  8.463908e-07   
1725  0.040072    0.687449    0.014018     0.247179  3.815070e-01   
1726  0.687449    0.687449    0.014018     0.247179  3.815070e-01   
1727  0.014018    0.687449    0.014018     0.247179  3.815070e-01   
1728  0.022135    0.046826    0.002592     0.023851  2.216664e-02   
1729  0.002592    0.046826    0.002592     0.023851  2.216664e-02   
1730  0.046826    0.046826    0.002592     0.023851  2.216664e-02   
1731  0.000142    0.000142    0.000070     0.000102  3.652155e-05   
1732  0.000094    0.000142    0.000070     0.000102  3.652155e-05   
1733  0.000070    0.000142    0.000070     0.000102  3.652155e-05   
1734  0.000072    0.005959    0.000072     0.002060  3.376524e-03   
1735  0.005959    0.005959    0.000072     0.002060  3.376524e-03   
1736  0.000150    0.005959    0.000072     0.002060  3.376524e-03   
1737  0.000508    0.030141    0.000088     0.010246  1.723141e-02   
1738  0.000088    0.030141    0.000088     0.010246  1.723141e-02   
1739  

In [80]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])