## e011 EDA
 * startified_k_fold の妥当性調査

In [1]:
import pandas as pd
import numpy as np
import gc
import pickle
import pyarrow.parquet as pq
from multiprocessing import Pool
from tqdm import tqdm_notebook as tqdm

import scipy
from scipy import signal
from scipy.signal import butter

from matplotlib import pyplot as plt
import seaborn as sns

import sys
sys.path.append('../../guchio_utils/')

In [2]:
#plt.rcParams['font.family'] = 'IPAPGothic' #全体のフォントを設定
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))
# %config InlineBackend.figure_formats = {'png', 'retina'}
%load_ext autoreload
%autoreload 1

### Stratified の性能を見てみる

In [2]:
#trn_df = pd.read_parquet('../inputs/origin/train.parquet.zip', compression='zip')
trn_df = pq.read_pandas('../inputs/origin/train.parquet').to_pandas()
trn_meta_df = pd.read_csv('../inputs/origin/metadata_train.csv')

In [3]:
with open('../oofs/e011_2019-01-17-17-42-05_0.5739_0.311_oofs.pkl', 'rb') as fin:
    oofs = pickle.load(fin)

In [5]:
oofs[0]

[array([   0,    1,    2, ..., 1746, 1747, 1748]),
 array([1575, 1576, 1577, ..., 3487, 3488, 3489]),
 array([3372, 3373, 3374, ..., 5267, 5268, 5269]),
 array([4768, 4769, 4815, ..., 6993, 6994, 6995]),
 array([6654, 6655, 6656, ..., 8709, 8710, 8711])]

In [10]:
for labels in oofs[0]:
#    print(trn_meta_df.set_index('signal_id').loc[labels].target.sum())
    print(trn_meta_df.set_index('signal_id').loc[labels].id_measurement.nunique() * 3, trn_meta_df.set_index('signal_id').loc[labels].reset_index().signal_id.nunique())

1743 1743
1746 1743
1752 1742
1749 1742
1743 1742


## e012 EDA
 * 各 oof の threshold から single model で submit したほうが良いのかを考える (普通 auc は rank avg) (model 毎に threshold は違うはず) 

In [2]:
#trn_df = pd.read_parquet('../inputs/origin/train.parquet.zip', compression='zip')
trn_df = pq.read_pandas('../inputs/origin/train.parquet').to_pandas()
trn_meta_df = pd.read_csv('../inputs/origin/metadata_train.csv')

In [11]:
with open('../oofs/e008_2019-01-17-08-04-32_0.5673_0.139_oofs.pkl', 'rb') as fin:
    oofs = pickle.load(fin)

In [13]:
df_elems = []
for i, oof in enumerate(zip(oofs[0], oofs[1])):
    signal_id, y_pred = oof
    _df = pd.DataFrame()
    _df['signal_id'] = signal_id
    _df['y_pred'] = y_pred
    _df['fold'] = i
    df_elems.append(_df)

oof_df = pd.concat(df_elems, axis=0)
oof_df

signal_id    y_pred  fold
0             3  0.507173     0
1             4  0.273839     0
2             5  0.338976     0
3            18  0.000015     0
4            19  0.000823     0
5            20  0.005122     0
6            33  0.000007     0
7            34  0.000046     0
8            35  0.000093     0
9            48  0.015403     0
10           49  0.004437     0
11           50  0.008285     0
12           78  0.000032     0
13           79  0.000013     0
14           80  0.000004     0
15           93  0.000628     0
16           94  0.001804     0
17           95  0.000577     0
18          108  0.000006     0
19          109  0.000003     0
20          110  0.000009     0
21          123  0.199064     0
22          124  0.493539     0
23          125  0.947652     0
24          129  0.000020     0
25          130  0.000095     0
26          131  0.000490     0
27          150  0.000033     0
28          151  0.000085     0
29          152  0.000020     0
...         ...       ...   ...
1710       8568  0.033424     4
1711       8569  0.009957     4
1712       8570  0.015641     4
1713       8589  0.126389     4
1714       8590  0.004462     4
1715       8591  0.004151     4
1716       8604  0.000480     4
1717       8605  0.185830     4
1718       8606  0.022910     4
1719       8619  0.000192     4
1720       8620  0.000008     4
1721       8621  0.000007     4
1722       8634  0.000080     4
1723       8635  0.000033     4
1724       8636  0.000109     4
1725       8643  0.000008     4
1726       8644  0.000004     4
1727       8645  0.000016     4
1728       8652  0.000010     4
1729       8653  0.000013     4
1730       8654  0.000013     4
1731       8667  0.000114     4
1732       8668  0.000027     4
1733       8669  0.000426     4
1734       8682  0.002104     4
1735       8683  0.000265     4
1736       8684  0.002556     4
1737       8697  0.000012     4
1738       8698  0.000069     4
1739       8699  0.000018     4

[8712 rows x 3 columns]

In [15]:
trn_meta_oof_df = trn_meta_df.merge(oof_df, on='signal_id', how='left')
trn_meta_oof_df

signal_id  id_measurement  phase  target    y_pred  fold
0             0               0      0       0  0.012684     3
1             1               0      1       0  0.008258     3
2             2               0      2       0  0.025044     3
3             3               1      0       1  0.507173     0
4             4               1      1       1  0.273839     0
5             5               1      2       1  0.338976     0
6             6               2      0       0  0.000416     4
7             7               2      1       0  0.000609     4
8             8               2      2       0  0.000498     4
9             9               3      0       0  0.000204     3
10           10               3      1       0  0.000033     3
11           11               3      2       0  0.000014     3
12           12               4      0       0  0.011002     2
13           13               4      1       0  0.058484     2
14           14               4      2       0  0.008206     2
15           15               5      0       0  0.000106     1
16           16               5      1       0  0.000027     1
17           17               5      2       0  0.000046     1
18           18               6      0       0  0.000015     0
19           19               6      1       0  0.000823     0
20           20               6      2       0  0.005122     0
21           21               7      0       0  0.000029     4
22           22               7      1       0  0.000011     4
23           23               7      2       0  0.000008     4
24           24               8      0       0  0.004895     3
25           25               8      1       0  0.002663     3
26           26               8      2       0  0.001489     3
27           27               9      0       0  0.000045     2
28           28               9      1       0  0.000146     2
29           29               9      2       0  0.000399     2
...         ...             ...    ...     ...       ...   ...
8682       8682            2894      0       0  0.002104     4
8683       8683            2894      1       0  0.000265     4
8684       8684            2894      2       0  0.002556     4
8685       8685            2895      0       0  0.000015     3
8686       8686            2895      1       0  0.000589     3
8687       8687            2895      2       0  0.000011     3
8688       8688            2896      0       0  0.000068     2
8689       8689            2896      1       0  0.002968     2
8690       8690            2896      2       0  0.004826     2
8691       8691            2897      0       0  0.000094     1
8692       8692            2897      1       0  0.000004     1
8693       8693            2897      2       0  0.000005     1
8694       8694            2898      0       0  0.001982     0
8695       8695            2898      1       0  0.000191     0
8696       8696            2898      2       0  0.012565     0
8697       8697            2899      0       0  0.000012     4
8698       8698            2899      1       0  0.000069     4
8699       8699            2899      2       0  0.000018     4
8700       8700            2900      0       0  0.000008     3
8701       8701            2900      1       0  0.000010     3
8702       8702            2900      2       0  0.000005     3
8703       8703            2901      0       0  0.000217     2
8704       8704            2901      1       0  0.000156     2
8705       8705            2901      2       0  0.000989     2
8706       8706            2902      0       0  0.000031     2
8707       8707            2902      1       0  0.000044     2
8708       8708            2902      2       0  0.000028     2
8709       8709            2903      0       0  0.085954     0
8710       8710            2903      1       0  0.006124     0
8711       8711            2903      2       0  0.000986     0

[8712 rows x 6 columns]

In [16]:
sys.path.append('../tools/utils/')
from metrics import calc_best_MCC

In [19]:
# threshold 全然違うやんけ...
for fold in range(5):
    mcc_df = trn_meta_oof_df.query(f'fold == {fold}')
    best_MCC, best_thresh = calc_best_MCC(mcc_df.target, mcc_df.y_pred)
    print(best_MCC, best_thresh)

100%|██████████| 30/30 [00:00<00:00, 682.27it/s]

0.5817122285912858 0.10424137931034483
0.5273301399042729 0.5860344827586207
0.5952264597279228 0.20748275862068966
0.6276506515467083 0.6548620689655172
0.6300460299735168 0.34513793103448276


In [20]:
# 単に concat したら threshold はこんな感じ
calc_best_MCC(trn_meta_oof_df.target, trn_meta_oof_df.y_pred)

100%|██████████| 30/30 [00:00<00:00, 593.41it/s]


(0.567333198083413, 0.1386551724137931)

In [52]:
from metrics import calc_MCC

In [54]:
# こんなかんじで本当に良くなる...？
# あ、でも test 時には変わるか
for fold in range(5):
    mcc_df = trn_meta_oof_df.query(f'fold == {fold}')
    MCC = calc_MCC(mcc_df.target, mcc_df.y_pred, thresh=0.1386551724137931)
    print(MCC)

0.5736031038490991
0.4760015946100805
0.561058906688545
0.5897363271372071
0.6218053132183833


In [55]:
# bins 上げると...？
calc_best_MCC(trn_meta_oof_df.target, trn_meta_oof_df.y_pred, bins=3000)

100%|██████████| 3000/3000 [00:05<00:00, 568.58it/s]


(0.5702475839248895, 0.13411103701233743)

In [35]:
# rank avg してみる
# trn_meta_oof_df = trn_meta_oof_df.set_index('signal_id')
trn_meta_oof_df['ranked_preds'] = 0.

for fold in range(5):
    mcc_df = trn_meta_oof_df.query(f'fold == {fold}')
    trn_meta_oof_df.loc[mcc_df.index, 'ranked_preds'] = ((mcc_df.y_pred.rank() - 1) / (mcc_df.shape[0] - 1))
    
trn_meta_oof_df   

id_measurement  phase  target    y_pred  fold  ranked_preds
signal_id                                                             
0                       0      0       0  0.012684     3      0.882319
1                       0      1       0  0.008258     3      0.868542
2                       0      2       0  0.025044     3      0.903559
3                       1      0       1  0.507173     0      0.965557
4                       1      1       1  0.273839     0      0.956372
5                       1      2       1  0.338976     0      0.959816
6                       2      0       0  0.000416     4      0.633698
7                       2      1       0  0.000609     4      0.680276
8                       2      2       0  0.000498     4      0.657274
9                       3      0       0  0.000204     3      0.577497
10                      3      1       0  0.000033     3      0.311137
11                      3      2       0  0.000014     3      0.161309
12                      4      0       0  0.011002     2      0.873134
13                      4      1       0  0.058484     2      0.928243
14                      4      2       0  0.008206     2      0.863949
15                      5      0       0  0.000106     1      0.501148
16                      5      1       0  0.000027     1      0.278416
17                      5      2       0  0.000046     1      0.363375
18                      6      0       0  0.000015     0      0.250861
19                      6      1       0  0.000823     0      0.731343
20                      6      2       0  0.005122     0      0.845006
21                      7      0       0  0.000029     4      0.271995
22                      7      1       0  0.000011     4      0.137435
23                      7      2       0  0.000008     4      0.102933
24                      8      0       0  0.004895     3      0.842710
25                      8      1       0  0.002663     3      0.807692
26                      8      2       0  0.001489     3      0.762916
27                      9      0       0  0.000045     2      0.346728
28                      9      1       0  0.000146     2      0.531573
29                      9      2       0  0.000399     2      0.638921
...                   ...    ...     ...       ...   ...           ...
8682                 2894      0       0  0.002104     4      0.782634
8683                 2894      1       0  0.000265     4      0.573893
8684                 2894      2       0  0.002556     4      0.799310
8685                 2895      0       0  0.000015     3      0.186567
8686                 2895      1       0  0.000589     3      0.691160
8687                 2895      2       0  0.000011     3      0.133180
8688                 2896      0       0  0.000068     2      0.418485
8689                 2896      1       0  0.002968     2      0.803100
8690                 2896      2       0  0.004826     2      0.835247
8691                 2897      0       0  0.000094     1      0.482204
8692                 2897      1       0  0.000004     1      0.021240
8693                 2897      2       0  0.000005     1      0.036739
8694                 2898      0       0  0.001982     0      0.796211
8695                 2898      1       0  0.000191     0      0.593571
8696                 2898      2       0  0.012565     0      0.881745
8697                 2899      0       0  0.000012     4      0.152961
8698                 2899      1       0  0.000069     4      0.389304
8699                 2899      2       0  0.000018     4      0.217366
8700                 2900      0       0  0.000008     3      0.086108
8701                 2900      1       0  0.000010     3      0.120551
8702                 2900      2       0  0.000005     3      0.028703
8703                 2901      0       0  0.000217     2      0.575775
8704                 2901      1       0  0.000156     2      0.539610
8705                 2901      2   

In [42]:
# rank avg したら threshold 悪くなったぞ...
for fold in range(5):
    mcc_df = trn_meta_oof_df.query(f'fold == {fold}')
    best_MCC, best_thresh = calc_best_MCC(mcc_df.target, mcc_df.ranked_preds)
    print(best_MCC, best_thresh)

100%|██████████| 30/30 [00:00<00:00, 733.98it/s]

0.5806245298518179 0.9301724137931034
0.48543450491005197 0.9645862068965517
0.5622267333313686 0.9645862068965517
0.6161803114136581 0.9645862068965517
0.6119923581769747 0.9645862068965517


In [49]:
# bins をちょうせいすればましになった
for fold in range(5):
    mcc_df = trn_meta_oof_df.query(f'fold == {fold}')
    best_MCC, best_thresh = calc_best_MCC(mcc_df.target, mcc_df.ranked_preds, bins=3000)
    print(best_MCC, best_thresh)

  3%|▎         | 78/3000 [00:00<00:03, 777.19it/s]

0.5850331044971155 0.9410966988996331


  2%|▏         | 74/3000 [00:00<00:03, 739.08it/s]

0.5273301399042729 0.97537279093031


  2%|▏         | 72/3000 [00:00<00:04, 717.41it/s]

0.5952264597279228 0.9547405801933977


  2%|▏         | 71/3000 [00:00<00:04, 701.20it/s]

0.6276854003058253 0.9603977992664221


100%|██████████| 3000/3000 [00:04<00:00, 669.88it/s]

0.6300460299735168 0.9593994664888296


In [50]:
# 結局 bin の値に敏感になってるきがする
calc_best_MCC(trn_meta_oof_df.target, trn_meta_oof_df.ranked_preds, bins=3000)

100%|██████████| 3000/3000 [00:05<00:00, 590.52it/s]


(0.568471124988459, 0.9547405801933977)

In [51]:
# bins をちょうせいすればましになった
for fold in range(5):
    mcc_df = trn_meta_oof_df.query(f'fold == {fold}')
    MCC = calc_MCC(mcc_df.target, mcc_df.ranked_preds, thresh=0.9547405801933977)
    print(MCC)

0.5437837740064833
0.4724930871318122
0.5952264597279228
0.614717199923815
0.6172836636520752


In [59]:
e008_df = pd.read_csv('../submissions/e008_2019-01-17-08-04-32_0.5673_0.139_sub.csv.gz', compression='gzip')
e008_df = pd.read_csv('../submissions/e008_2019-01-17-08-04-32_0.5673_0.139_sub.csv.gz', compression='gzip')
e012_df = pd.read_csv('../submissions/e012_2019-01-17-22-47-11_0.5947_sub.csv.gz', compression='gzip')

In [63]:
pd.concat([e008_df.target, e012_df.target], axis=1).corr()

target    target
target  1.000000  0.754826
target  0.754826  1.000000

In [64]:
e008_df.target.sum(), e012_df.target.sum()

(978, 569)

In [65]:
e008_df.shape

(20337, 2)